name: ci
on:
  push:
    branches:
    - ng
  pull_request:
jobs:
 linux:
    uses: ChristopherHX/linux-packaging-scripts/.github/workflows/main.yml@main
    with:
      mcpelauncher-ref: ${{ github.sha }}
 macOS:
    uses: ChristopherHX/osx-packaging-scripts/.github/workflows/main.yml@main
    with:
      mcpelauncher-ref: ${{ github.sha }}