name: ci
on:
  push:
    branches:
    - ng
  pull_request:
jobs:
 linux:
    uses: minecraft-linux/appimage-builder/.github/workflows/main.yml@main
    with:
      mcpelauncher-ref: ${{ github.sha }}
 macOS:
    uses: minecraft-linux/macos-builder/.github/workflows/main.yml@main
    with:
      mcpelauncher-ref: ${{ github.sha }}
